az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS3-Jumpbox"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS3-Network"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS3-PrivateCloud"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab10@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab11@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"

az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab12@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab13@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab14@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab15@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab16@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"

az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab17@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"

az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab18@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"



az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab19@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab20@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"

az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab21@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab22@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab23@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab24@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab25@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab26@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"



az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab27@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"


az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab28@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"



az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab29@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"



az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Jumpbox"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Network"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-Operational"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS01-PrivateCloud"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Jumpbox"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Network"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-Operational"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS02-PrivateCloud"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Jumpbox"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Network"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-Operational"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "Mh-AVS07-PrivateCloud"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Jumpbox"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Network"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-Operational"
az role assignment create --assignee "Lab30@vmwaresales101outlook.onmicrosoft.com" --role "Contributor" --resource-group "MH-OP-00-PrivateCloud"
